### ISSUE TITLE
Too many disconnected leaf nodes in function graphs

### ISSUE THREAD

**Issue by wlandau** [mbojan/pkgnet#8]
I am really excited for this package! It is a promising improvement relative to [`CodeDepends` call graphs](https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html#call-graphs) (ref: https://github.com/duncantl/CodeDepends/issues/18).

For `CreatePackageReport(pkg_name = "liteq")`, here are some screenshots of the function graph. `ack()` calls `db_ack()` and `consume()` calls `db_consume()`, but the graph does not show this information.

![screenshot_20180414_211701](https://user-images.githubusercontent.com/1580860/38773973-98ea6136-4029-11e8-9c45-133245587f74.png)

![screenshot_20180414_211737](https://user-images.githubusercontent.com/1580860/38773974-9c87d7e2-4029-11e8-9d26-236efc4fd0a4.png)

**Comment by wlandau** [comment]
Oops. Sorry, I confused this package with https://github.com/UptakeOpenSource/pkgnet.

**Comment by mbojan** [comment]
No problem @wlandau :)
The other `pkgnet` looks great, so thanks for the tip! :)
